# Generated by Django 5.2.8 on 2025-11-26 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grabber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome do Grabber')),
                ('grab', models.JSONField(default=dict, verbose_name='Dados do Grab')),
            ],
            options={
                'verbose_name': 'Grabber',
                'verbose_name_plural': 'Grabbers',
            },
        ),
    ]
